import routeMetadata from './route-meta.json';

export const routeMeta = routeMetadata;

export const imageManifest = {
  'land-hero': {
    src: '/images/originals/2026-08-02/photo-015.jpeg',
    width: 1024,
    height: 768,
    widths: [480, 960, 1024],
    alt: 'Breed overzicht van kas, werkplaats en picknicktafel op Land van Jan',
    focalPoint: '51% 48%',
  },
  buitenplek: {
    src: '/images/buitenplek.jpeg',
    width: 1512,
    height: 2016,
    widths: [480, 960, 1512],
    alt: 'Beschutte buitenplek tussen de bomen op Land van Jan',
    focalPoint: '50% 48%',
  },
  boomgaard: {
    src: '/images/boomgaard-hd.jpeg',
    width: 1512,
    height: 2016,
    widths: [480, 960, 1512],
    alt: 'Fruitbomen en groen in de boomgaard van Land van Jan',
    focalPoint: '50% 44%',
  },
  gemeenschap: {
    src: '/images/gemeenschap-hd.jpeg',
    width: 2016,
    height: 1512,
    widths: [480, 960, 1600, 2016],
    alt: 'Mensen ontmoeten elkaar buiten op Land van Jan',
    focalPoint: '50% 50%',
  },
  'kas-binnen': {
    src: '/images/kas-binnen-hd.jpeg',
    width: 2016,
    height: 1512,
    widths: [480, 960, 1600, 2016],
    alt: 'Planten en werktafels binnen in de kas van Land van Jan',
    focalPoint: '50% 46%',
  },
  'kas-buiten': {
    src: '/images/kas-buiten-hd.jpeg',
    width: 2016,
    height: 1512,
    widths: [480, 960, 1600, 2016],
    alt: 'De kas van Land van Jan gezien vanuit het groen',
    focalPoint: '50% 48%',
  },
  'kas-detail': {
    src: '/images/originals/2026-08-02/photo-006.jpeg',
    width: 768,
    height: 1024,
    widths: [384, 768],
    alt: 'Koperen bloemornament tussen groene planten in de kas',
    focalPoint: '60% 50%',
  },
  werkplaats: {
    src: '/images/werkplaats-hd.jpeg',
    width: 2016,
    height: 1512,
    widths: [480, 960, 1600, 2016],
    alt: 'Werkplek voor handwerk en maken op Land van Jan',
    focalPoint: '50% 50%',
  },
  'ankh-kunst': {
    src: '/images/originals/2026-08-02/photo-035.jpeg',
    width: 768,
    height: 1024,
    widths: [384, 768],
    alt: 'Messing ankh op een houten schijf tussen paarse en roze bloemen',
    focalPoint: '50% 52%',
  },
  muziek: {
    src: '/images/originals/2026-08-02/photo-034.jpeg',
    width: 724,
    height: 1086,
    widths: [362, 724],
    alt: 'Muzikant met hoed speelt handpan in het groen',
    focalPoint: '49% 43%',
  },
  appel: {
    src: '/images/appel-ankh.jpeg',
    width: 360,
    height: 638,
    widths: [360],
    alt: 'Appel en handgemaakt symbool als seizoensbeeld van het land',
    focalPoint: '50% 50%',
  },
  toekomst: {
    src: '/images/toekomstvisualisatie.png',
    width: 1086,
    height: 1448,
    widths: [480, 960, 1086],
    alt: 'Toekomstvisualisatie van een rijk begroeid Land van Jan',
    focalPoint: '50% 48%',
    generated: true,
  },
  'erf-ontmoeting': {
    src: '/images/originals/2026-08-02/photo-016.jpeg',
    width: 1024,
    height: 768,
    widths: [480, 960, 1024],
    alt: 'Breed erf met bomen, schuurtjes en een beschutte ontmoetingsplek',
    focalPoint: '53% 48%',
  },
  'boomgaard-breed': {
    src: '/images/originals/2026-08-02/photo-026.jpeg',
    width: 1024,
    height: 768,
    widths: [480, 960, 1024],
    alt: 'Brede bomenrij en open grasveld in de boomgaard',
    focalPoint: '43% 47%',
  },
  'kas-werkbank': {
    src: '/images/originals/2026-08-02/photo-013.jpeg',
    width: 1024,
    height: 768,
    widths: [480, 960, 1024],
    alt: 'Werkbanken en gereedschap in een glazen kas',
    focalPoint: '57% 48%',
  },
  'kas-ruimte': {
    src: '/images/originals/2026-08-02/photo-014.jpeg',
    width: 1024,
    height: 768,
    widths: [480, 960, 1024],
    alt: 'Open ruimte met bakstenen vloer en planten in de kas',
    focalPoint: '58% 52%',
  },
  appelboom: {
    src: '/images/originals/2026-08-02/photo-024.jpeg',
    width: 768,
    height: 1024,
    widths: [384, 768],
    alt: 'Appelboom met roodgroene appels voor de boomgaard',
    focalPoint: '30% 48%',
  },
  kersen: {
    src: '/images/originals/2026-08-02/photo-033.jpeg',
    width: 768,
    height: 1024,
    widths: [384, 768],
    alt: 'Rode en oranje kersen tussen groene bladeren tegen een blauwe lucht',
    focalPoint: '54% 46%',
  },
  'ankh-kristal': {
    src: '/images/originals/2026-08-02/photo-036.jpeg',
    width: 659,
    height: 1192,
    widths: [330, 659],
    alt: 'Twee ankh-objecten met kristallen tussen roze rozenblaadjes',
    focalPoint: '49% 45%',
  },
};

export function responsiveSource(key) {
  const image = imageManifest[key];
  const basename = image.src.split('/').pop().replace(/\.(jpeg|jpg|png)$/i, '');
  return image.widths.map((width) => `/images/responsive/${basename}-${width}.webp ${width}w`).join(', ');
}

export const pageContent = {
  '/over-het-land': {
    eyebrow: 'OVER HET LAND',
    title: <>Een open plek<br />om te maken,<br /><em>te delen</em> en<br />te groeien.</>,
    text: 'Kas, boomgaard, muziek en een tafel buiten. Land van Jan groeit met de mensen en seizoenen die hier samenkomen.',
    hero: 'erf-ontmoeting',
    detail: 'kas-binnen',
    heading: 'Tussen rivierland en boomgaard',
    body: 'Huissen ligt in het landschap rond de Nederrijn: een plek van rivierklei, dijken, teelt en oude routes. Op dit erf komen grond, voedsel, handwerk en ontmoeting stap voor stap samen.',
    points: ['Kas en moestuin als plek om te leren', 'Fruitbomen, stekjes en seizoenswerk', 'Ruimte voor makers, rust en ontmoeting'],
    gallery: ['kas-buiten', 'boomgaard-breed', 'werkplaats'],
    labels: ['De kas', 'De boomgaard', 'Werk & maken'],
    quote: 'We bouwen niet alleen aan een terrein, maar aan een ritme waarin mensen en seizoenen samenkomen.',
  },
  '/agenda': {
    eyebrow: 'AGENDA',
    title: <>Tijd om samen<br /><em>naar buiten</em> te gaan.</>,
    text: 'Kleine activiteiten met aandacht voor het seizoen, de plek en elkaar.',
    hero: 'kas-binnen',
    detail: 'land-hero',
    heading: 'Wat je kunt verwachten',
    body: 'De agenda beweegt mee met het seizoen. Sommige dagen zijn praktisch, andere rustig, creatief of gericht op samen eten en luisteren.',
    points: ['Zaaien, oogsten en werken met de bodem', 'Rondleidingen en kleine proeverijen', 'Muziek, creatieve middagen en retraites'],
    gallery: ['kas-ruimte', 'gemeenschap', 'kas-werkbank'],
    labels: ['Ruimte voor activiteiten', 'Samen aan tafel', 'Werken en leren'],
    quote: 'Kom zoals je bent. Je hoeft niets te kunnen om mee te doen.',
  },
  '/verhalen': {
    eyebrow: 'VERHALEN',
    title: <>Makers, muziek<br />en <em>natuur.</em></>,
    text: 'Op het land krijgen ritueel, handwerk, voedsel en ontmoeting een plek.',
    hero: 'boomgaard-breed',
    detail: 'gemeenschap',
    heading: 'Dingen die hier betekenis krijgen',
    body: 'Een handgemaakt object, een instrument, een oogst uit de kas of een gesprek aan tafel: de verhalen van het land gaan over aandacht en vakmanschap.',
    points: ['Handgemaakte kunst en symboliek', 'Muziek en klank in de buitenlucht', 'Voedsel, planten en verhalen uit het seizoen'],
    gallery: ['ankh-kunst', 'muziek', 'kersen'],
    labels: ['Kunst & symboliek', 'Muziek op het land', 'Oogst & seizoen'],
    quote: 'Een plek wordt bijzonder door de verhalen die mensen er samen aan toevoegen.',
  },
  '/contact': {
    eyebrow: 'CONTACT',
    title: <>Kom kijken.<br /><em>Of bouw mee.</em></>,
    text: 'Wil je langskomen, een activiteit organiseren of bijdragen met tijd, kennis of materiaal? Laat van je horen.',
    hero: 'land-hero',
    detail: 'kas-buiten',
    heading: 'Een eerste stap is genoeg',
    body: 'Je hoeft niet alles al te weten. Vertel wat je aanspreekt: een bezoek, een idee, een vaardigheid, een workshop of gewoon nieuwsgierigheid.',
    points: ['Kom langs voor een eerste kennismaking', 'Denk mee over activiteiten of het programma', 'Draag bij met tijd, kennis of materiaal'],
    gallery: ['gemeenschap', 'boomgaard', 'werkplaats'],
    labels: ['Ontmoeten', 'Rondkijken', 'Samen bouwen'],
    quote: 'Een kort bericht is genoeg om de eerste stap te zetten.',
  },
  '/lid-worden': {
    eyebrow: 'WORD LID',
    title: <>Samen dragen,<br /><em>samen doen.</em></>,
    text: 'Voor €5 per maand help je het land onderhouden en ontvang je updates, activiteiten en vier bijeenkomsten per jaar.',
    hero: 'gemeenschap',
    detail: 'ankh-kunst',
    heading: 'Een klein bedrag, een gezamenlijke basis',
    body: 'Een lidmaatschap helpt het land onderhouden en maakt ruimte voor mensen die niet vanzelf financiële ruimte hebben. Je ontvangt updates en uitnodigingen om aan te haken.',
    points: ['€5 per maand als bijdrage aan het land', 'Updates, uitnodigingen en online inspiratie', 'Vier bijeenkomsten per jaar op het land'],
    gallery: ['kas-binnen', 'boomgaard-breed', 'buitenplek'],
    labels: ['De plek verzorgen', 'De oogst delen', 'Samen aanwezig zijn'],
    quote: 'Lid zijn betekent niet alleen ontvangen, maar ook samen ruimte mogelijk maken.',
  },
};
